version: '2'

services:
  fpm:
    image: akeinhell/redfoxbot
    links:
      - db
      - redis
    volumes:
      - ../:/var/www
    restart: always

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "63791:6379"
    volumes:
      - ./data/redis:/data

  lb:
    image: dockercloud/haproxy
    ports:
      - 4430:80
      - 8008:80
    links:
      - fpm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
