version: '2'

services:
  fpm:
    image: ttaranto/docker-nginx-php7
    ports:
      - 8008:80
    links:
      - db
      - redis
    volumes:
      - ../:/var/www
    restart: always

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./docker/data/postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "63791:6379"
    volumes:
      - ./docker/data/redis:/data
